name: Numeron CI

on:
  pull_request:
    branches:
      - master
      - release-*
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - master
      - release-*
    paths:
      - "**"
      - "!**.md"
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  check:
    runs-on: ubuntu-latest
    # Default steps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Check Numeron
        run: ./gradlew check
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v3