name: Numeron CI

on:
  pull_request:
    branches:
      - master
      - release-*
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - master
      - release-*
    paths:
      - "**"
      - "!**.md"
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  check:
    runs-on: ubuntu-latest
    # Default steps
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          cache: 'gradle'
          java-version: 17
      - name: Check Numeron
        run: chmod +x ./gradlew && ./gradlew check
      - name: Upload coverage reports to Codecov
        uses: actions/checkout@v1
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov .
      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}